### ISSUE TITLE
error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: ['basic']"}

### ISSUE THREAD

**Issue by asarm** [kfiross/flutter_instagram_image_picker#2]
Why I'm getting this error: error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: ['basic']"}

**Comment by augustmuir** [comment]
You need to navigate to the package
\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_instagram_image_picker-0.3.1\lib\screens.dart
(Or in flutter go to .packages and find the package location)

Change the client ID here:
`  String url =
        "https://instagram.com/oauth/authorize/?client_id=1677ed07ddd54db0a70f14f9b1435579&redirect_uri=http://instagram.pixelunion.net&&scope=user_profile,user_media&response_type=token&hl=en";
`
To your own client ID through Facebook developer portal.

They updated the API in June and old API keys/Client ID's no longer work. The Client ID now has to be a updated App ID with the new API.

**Comment by kfiross** [comment]
@augustkimo Yes you right, the API has changed and I'm working now on an update to make things work correctly again.

**Comment by kfiross** [comment]
@augustkimo @asarm  Sorry for the delay, but a big update coming soon!

**Comment by kfiross** [comment]
Using now v1.0.0 with other API (I made for), so all working now
