### ISSUE TITLE
not able to get instagram photos

### ISSUE THREAD

**Issue by archanasorout** [kfiross/flutter_instagram_image_picker#3]
i am not able to get instagram photos in my simultor and in real device. i have downloaded the flutter project from the github and then run the example then put the login details after run the project and then we were moved the image picker page but i am not getting anything their

**Comment by kfiross** [comment]
For the first time, it will ask you for a login from device (I'm pretty sure an android, it's for the login process of verification).
Can you check again today?

**Comment by archanasorout** [comment]
Thanks for the reply Kfiross. yes it is asking for login but the  problem occur after login process (successfully login but not showing any kind of photos on that page )
actually can you please  tell me before using this package , is their any kind of formalities that we need to be done  like Facebook(because we can not access directly data from Facebook, so is it same in Instagram also? if yes then please give us proper explanation so it will be more helpful for us. ) because I don't have too much idea about this

**Comment by kfiross** [comment]
@archanasorout 
You can check version 2.0.0
Only public images can be shown now
